from django.db import models

class FlipRetDB(models.Model):
	
	ReturnApprovalDate=models.CharField(max_length=100,null=True)
	ReturnRequestedDate=models.CharField(max_length=100,null=True)
	ReturnID=models.CharField(max_length=100,null=True)
	TrackingId=models.CharField(max_length=100,null=True)
	OrderId=models.CharField(max_length=100,null=True)
	ORDERITEMID=models.CharField(max_length=100,null=True)
	ReturnType=models.CharField(max_length=100,null=True)
	ReturnSubType=models.CharField(max_length=100,null=True)
	ReplacementOrderItemID=models.CharField(max_length=100,null=True)
	ReturnStatus=models.CharField(max_length=100,null=True)
	SKU=models.CharField(max_length=100,null=True)
	FSN=models.CharField(max_length=100,null=True)
	Product=models.CharField(max_length=300,null=True)
	FFType=models.CharField(max_length=100,null=True)
	ReturnDeliveryPromiseDate=models.CharField(max_length=100,null=True)
	PickedUpDate=models.CharField(max_length=100,null=True)
	OutForDeliveryDate=models.CharField(max_length=100,null=True)
	CompletedDate=models.CharField(max_length=100,null=True)
	ReturnReason=models.CharField(max_length=200,null=True)
	ReturnSubReason=models.CharField(max_length=200,null=True)
	Comments=models.CharField(max_length=1000,null=True)
	BuyerName=models.CharField(max_length=100,null=True)
	BuyerAddress=models.CharField(max_length=300,null=True)
	ReverseLogisticFormNo=models.CharField(max_length=100,null=True)
	ForwardLogisticFormNo=models.CharField(max_length=100,null=True)
	TotalPrice=models.CharField(max_length=100,null=True)
	Quantity=models.CharField(max_length=100,null=True)
	GoodQuantity=models.CharField(max_length=100,null=True)
	BadQuantity=models.CharField(max_length=100,null=True)
	VendorName=models.CharField(max_length=100,null=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)
	def __str__(self):
		return self.TrackingId+"^^"+self.OrderId+"^^"+self.ORDERITEMID+"^^"+self.SKU+"^^"+self.Product+"^^"+self.CompletedDate

class SnapRetDB(models.Model):
	Name=models.CharField(max_length=300,null=True)
	Attribute=models.CharField(max_length=100,null=True)
	SUPC=models.CharField(max_length=100,null=True)
	SKU=models.CharField(max_length=100,null=True)
	SuborderID=models.CharField(max_length=100,null=True)
	ReturnInitiatedOn=models.CharField(max_length=100,null=True)
	ReturnDeliveredOn=models.CharField(max_length=100,null=True)
	FulfilmentMode=models.CharField(max_length=100,null=True)
	AWBNumber=models.CharField(max_length=100,null=True)
	SellingPrice=models.CharField(max_length=100,null=True)
	PaymentMode=models.CharField(max_length=100,null=True)
	OrderDate=models.CharField(max_length=100,null=True)
	DeductedAmount=models.CharField(max_length=100,null=True)
	DuePaymentDate=models.CharField(max_length=100,null=True)
	DeductedAmount_Wallet=models.CharField(max_length=100,null=True)
	DuePaymentDate_Wallet=models.CharField(max_length=100,null=True)
	ReturnAcceptedon=models.CharField(max_length=100,null=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)
	def __str__(self):
		return self.Name+"^^"+self.SKU+"^^"+self.SuborderID+"^^"+self.ReturnDeliveredOn+"^^"+self.AWBNumber

class SnapRetBuyerDB(models.Model):
	Name=models.CharField(max_length=300,null=True)
	SUPC=models.CharField(max_length=100,null=True)
	SKU=models.CharField(max_length=100,null=True)
	SuborderID=models.CharField(max_length=100,null=True)
	ReturnInitiatedOn=models.CharField(max_length=100,null=True)
	ReturnDeliveredOn=models.CharField(max_length=100,null=True)
	FulfilmentMode=models.CharField(max_length=100,null=True)
	AWBNumber=models.CharField(max_length=100,null=True)
	SellingPrice=models.CharField(max_length=100,null=True)
	PaymentMode=models.CharField(max_length=100,null=True)
	OrderDate=models.CharField(max_length=100,null=True)
	ShippingDate=models.CharField(max_length=100,null=True)
	Reason=models.CharField(max_length=500,null=True)
	ReturnAcceptedon=models.CharField(max_length=100,null=True)
	RTVCode=models.CharField(max_length=100,null=True)
	DeductedAmount=models.CharField(max_length=100,null=True)
	DuePaymentDate=models.CharField(max_length=100,null=True)
	Status=models.CharField(max_length=100,null=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)
	def __str__(self):
		return self.Name+"^^"+self.SKU+"^^"+self.SuborderID+"^^"+self.ReturnDeliveredOn+"^^"+self.AWBNumber