# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipretdb',
            name='IDflip',
        ),
        migrations.RemoveField(
            model_name='snapretdb',
            name='IDsnap',
        ),
        migrations.AddField(
            model_name='flipretdb',
            name='x',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
