# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_auto_20161023_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapRetBuyerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('SUPC', models.CharField(max_length=100, null=True)),
                ('SKU', models.CharField(max_length=100, null=True)),
                ('SuborderID', models.CharField(max_length=100, null=True)),
                ('ReturnInitiatedOn', models.CharField(max_length=100, null=True)),
                ('ReturnDeliveredOn', models.CharField(max_length=100, null=True)),
                ('FulfilmentMode', models.CharField(max_length=100, null=True)),
                ('AWBNumber', models.CharField(max_length=100, null=True)),
                ('SellingPrice', models.CharField(max_length=100, null=True)),
                ('PaymentMode', models.CharField(max_length=100, null=True)),
                ('OrderDate', models.CharField(max_length=100, null=True)),
                ('ShippingDate', models.CharField(max_length=100, null=True)),
                ('Reason', models.CharField(max_length=500, null=True)),
                ('ReturnAcceptedon', models.CharField(max_length=100, null=True)),
                ('RTV', models.CharField(max_length=100, null=True)),
                ('DeductedAmount', models.CharField(max_length=100, null=True)),
                ('PaymentDate', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flipretdb',
            name='x',
        ),
    ]
