# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_auto_20161222_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapretbuyerdb',
            name='PaymentDate',
        ),
        migrations.RemoveField(
            model_name='snapretbuyerdb',
            name='RTV',
        ),
        migrations.AddField(
            model_name='snapretbuyerdb',
            name='DuePaymentDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snapretbuyerdb',
            name='RTVCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
