# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlipDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_On', models.CharField(max_length=100, null=True)),
                ('Shipment_ID', models.CharField(max_length=100, null=True)),
                ('ORDER_ITEM_ID', models.CharField(max_length=100, null=True)),
                ('Order_Id', models.CharField(max_length=100, null=True)),
                ('Order_State', models.CharField(max_length=100, null=True)),
                ('Order_Type', models.CharField(max_length=100, null=True)),
                ('FSN', models.CharField(max_length=100, null=True)),
                ('SKU', models.CharField(max_length=100, null=True)),
                ('Product', models.CharField(max_length=100, null=True)),
                ('Invoice_No', models.CharField(max_length=100, null=True)),
                ('VAT', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('Invoice_Date', models.CharField(max_length=100, null=True)),
                ('Invoice_Amount', models.IntegerField(null=True)),
                ('Selling_PPI', models.IntegerField(null=True)),
                ('Shipping_CPI', models.IntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price_inc_Subsidy', models.IntegerField(null=True)),
                ('Buyer_name', models.CharField(max_length=100, null=True)),
                ('Ship_to_name', models.CharField(max_length=100, null=True)),
                ('Address_Line_1', models.CharField(max_length=100, null=True)),
                ('Address_Line_2', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('PIN_Code', models.CharField(max_length=100, null=True)),
                ('Proc_SLA', models.CharField(max_length=100, null=True)),
                ('Dispatch_After_date', models.CharField(max_length=100, null=True)),
                ('Dispatch_by_date', models.CharField(max_length=100, null=True)),
                ('Form_requirement', models.CharField(max_length=100, null=True)),
                ('Tracking_ID', models.CharField(max_length=100, null=True)),
                ('Length', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('Breadth', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('Height', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('Weight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('Attachment', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courier', models.CharField(max_length=50, null=True)),
                ('Product', models.CharField(max_length=150, null=True)),
                ('Reference_Code', models.CharField(max_length=50, null=True)),
                ('Suborder_ID', models.CharField(max_length=100, null=True)),
                ('SKU_code', models.CharField(max_length=100, null=True)),
                ('AWB_Number', models.CharField(max_length=100, null=True)),
                ('Order_Verified_Date', models.CharField(max_length=100, null=True)),
                ('Order_Created_Date', models.CharField(max_length=100, null=True)),
                ('Customer_Name', models.CharField(max_length=100, null=True)),
                ('Shipping_Name', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('PinCode', models.CharField(max_length=100, null=True)),
                ('SellingPPI', models.CharField(max_length=100, null=True)),
                ('Tax_Amount_Percent', models.CharField(max_length=10, null=True)),
                ('IMEI', models.CharField(max_length=100, null=True)),
                ('Promised_ShipDate', models.CharField(max_length=100, null=True)),
                ('MRP', models.IntegerField(default=0)),
                ('Invoice_Code', models.CharField(max_length=100, null=True)),
                ('Fulfilment_mode', models.CharField(max_length=100, null=True)),
                ('Mobile_No', models.CharField(max_length=15, null=True)),
                ('Email_ID', models.CharField(max_length=100, null=True)),
                ('SUPC', models.CharField(max_length=100, null=True)),
                ('Attributes', models.CharField(max_length=100, null=True)),
                ('PaymentMode', models.CharField(max_length=50, null=True)),
                ('HandoverDate', models.CharField(max_length=100, null=True)),
                ('Courier_Code', models.CharField(max_length=100, null=True)),
                ('Oneship_Center_Name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
