# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-16 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpFile',
        ),
        migrations.RemoveField(
            model_name='files',
            name='FileSynced',
        ),
    ]
