# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161016_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdb',
            name='Tax_Amount_Percent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
