# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161017_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipdb',
            name='InvoiceID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snapdb',
            name='InvoiceID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
