# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161017_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='FileUploaded',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Address_Line_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Address_Line_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Attachment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Buyer_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Dispatch_After_date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Dispatch_by_date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='FSN',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Form_requirement',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='InvoiceID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Invoice_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Invoice_No',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='ORDER_ITEM_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Order_Id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Order_State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Order_Type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Ordered_On',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='PIN_Code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Proc_SLA',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Product',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='SKU',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Ship_to_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Shipment_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flipdb',
            name='Tracking_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paydb',
            name='OrderID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='AWB_Number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Attributes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Courier',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Courier_Code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Customer_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Email_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Fulfilment_mode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='HandoverDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='IMEI',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='InvoiceID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Invoice_Code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Oneship_Center_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Order_Created_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Order_Verified_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='PinCode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Product',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Promised_ShipDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Reference_Code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='SKU_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='SUPC',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='SellingPPI',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Shipping_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Suborder_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdb',
            name='Tax_Amount_Percent',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
